### ISSUE TITLE
Support for adding values with different units

### ISSUE THREAD

**Issue by ajbouh** [ericman314/UnitMath#13]
There are a number of scenarios where you would like to aggregate units of different types together in a "sum".

A simple example might be ingredients for a recipe. Native support for a unit sum makes it easy to do things like combine the ingredients for any number of recipes together with simple addition.

Beyond addition, there are other operations that make sense in the context of a UnitSum. For example there are two definitions of "inner product" that are valuable.

One is defined as the sum-product of "exact" unit matches, so `(2 egg + 2 tomato + 2 egg / day) • (3 egg) == 6 egg`

The other is the sum-product of "fuzzy" unit matches,
so `(1 egg / day + 1 croissant / mile) • (2 day + 4 mile) = (2 egg + 4 croissant)`

All of the above is implemented in https://observablehq.com/@ajbouh/math-js-with-unitsum

I'd love to contribute this upstream!

I should add that there are a few open questions, like what the names for these operations should be and how to avoid needing to override so many internal mathjs operations.

**Comment by ericman314** [comment]
Thank you for sharing, that looks really cool. I especially like this one: `(1 egg / day + 1 croissant / mile) • (2 day + 4 mile) = (2 egg + 4 croissant)`

Have you thought about publishing this as its own npm library? There might be some issues with adding this upstream, since your syntax which allows adding units of different dimensions (`egg` and `egg / day`) is not really compatible with the existing syntax which does not allow this. Maybe you could use math.js's array type to represent an aggregate sum? Whether you go that route or not, I think your code looks great and it would be pretty useful as its own library.

**Comment by ajbouh** [comment]
Thanks for the kind words!

I have fully integrated UnitSum into math.js in a way that is compatible
with existing syntax and semantics. It's closed under both addition and
scalar multiplication. It's also closed under both inner products I defined
previously.

I would actually like to integrate this directly into math.js itself since
that's how I'm using it and because it relies on overriding some internal
math.js primitive operations to define all the combinations of
scalar/UnitSum operations.

Perhaps this conversation should include the math.js maintainer?

**Comment by ericman314** [comment]
Sure, I think the best way is to open a new issue over at https://github.com/josdejong/mathjs/issues.

Good luck!
